name: Preview changes
on:
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    name: Preview Terraform changes
    permissions:
      actions: read
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download state from artifact
        uses: ./.github/actions/download-state
        with:
          encryption_key: ${{ secrets.ENCRYPTION_KEY }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Terraform
        uses: ./.github/actions/setup

      - name: Validate
        run: terraform validate

      - name: Plan
        env:
          TF_VAR_discord_token: ${{ secrets.DISCORD_BOT_TOKEN }}
          TF_VAR_server_id: ${{ secrets.DISCORD_SERVER_ID }}
        run: |
          terraform plan -out .planfile

      - name: Post PR comment
        uses: borchero/terraform-plan-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          planfile: .planfile
